# Generated by Django 2.0.3 on 2018-05-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180414_0405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
