# Generated by Django 2.0.3 on 2018-05-17 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0003_products_productservicecentres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0003_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.IntegerField(primary_key=True, serialize=False)),
                ('Problem', models.CharField(max_length=500)),
                ('OrderConfirmation', models.BooleanField(default=False)),
                ('Dateofrequest', models.DateField()),
                ('NumOfrepairdays', models.IntegerField()),
                ('ServiceCentreId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repairs.Service_Centres')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ProfileId', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('PhoneNum', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='UserId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysite.Profile'),
        ),
    ]
