# Generated by Django 2.0.3 on 2018-05-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180517_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ServiceCentreId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
