# Generated by Django 2.0.3 on 2018-05-19 06:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repairs', '0003_products_productservicecentres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('Problem', models.CharField(max_length=500)),
                ('OrderConfirmation', models.BooleanField(default=False)),
                ('Dateofrequest', models.DateField(default=datetime.datetime.today)),
                ('NumOfrepairdays', models.IntegerField(default=5)),
                ('centre', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='selectcentre', to='repairs.Service_Centres')),
                ('product', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='placeorder', to='repairs.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ProfileId', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('PhoneNum', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
