# Generated by Django 2.0.3 on 2018-05-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repairs', '0003_products_productservicecentres'),
        ('orders', '0003_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
