# Generated by Django 2.0.3 on 2018-05-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180519_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
