# Generated by Django 2.0.3 on 2018-05-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180519_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordering',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ordering',
        ),
    ]
