# Generated by Django 2.0.3 on 2018-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_ordering_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='PhoneNum',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ProfileId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
