# Generated by Django 2.0.3 on 2018-05-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180520_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordering',
            name='owner',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
