# Generated by Django 2.0.3 on 2018-05-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180520_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='centre',
        ),
    ]
