# Generated by Django 2.0.3 on 2018-05-22 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_ordering_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
