# Generated by Django 2.0.3 on 2018-05-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20180522_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordering',
            name='username',
        ),
        migrations.AddField(
            model_name='ordering',
            name='user',
            field=models.CharField(default=16, max_length=20),
            preserve_default=False,
        ),
    ]
