# Generated by Django 2.0.3 on 2018-05-26 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180525_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordering',
            name='Dateofrequest',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
